## 聚合函数&基本统计函数

In [1]:
import numpy as np

In [2]:
# 求和
x = np.arange(1,6)
np.add.reduce(x)

15

In [4]:
# 求所有元素的乘积
np.multiply.reduce(x)

120

In [7]:
# 外积(九九乘法表)
n = np.arange(1,10)
np.multiply.outer(n,n)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [46]:
one = np.random.randint(1,10,[4,5])
one

array([[3, 7, 9, 3, 6],
       [4, 2, 4, 2, 4],
       [7, 5, 9, 8, 3],
       [4, 3, 6, 3, 9]])

In [47]:
# 求和
np.sum(one,axis=0)  # 按列求和

array([18, 17, 28, 16, 22])

In [48]:
np.sum(one,axis=1)  # 按行求和

array([28, 16, 32, 25])

In [49]:
# 求最值
np.max(one,axis=0)  # 按列求

array([7, 7, 9, 8, 9])

In [50]:
np.max(one,axis=1)  # 按行求

array([9, 4, 9, 9])

In [51]:
np.max(one)  # 求所有元素最大值

9

In [52]:
# 取最值索引
np.argmax(one,axis=0)  # 按列取

array([2, 0, 0, 2, 3], dtype=int64)

In [53]:
np.argmax(one,axis=1)  # 按行取

array([2, 0, 2, 4], dtype=int64)

In [55]:
np.argmax(one)  # 求所有元素最大值索引(按行从0数)

2

In [57]:
# 判断是否存在元素为真
np.any(one)

True

In [58]:
# 判断是否所有元素为真
np.all(one)

True

一些具有缺失值的数组运算时可以在聚合函数前加一个nan