In [2]:
import numpy as np

## 外部写入

In [7]:
datas = np.genfromtxt('sale_datas.txt',  # 文件名 
                      delimiter=',',  # 分隔符
                      skip_header=1)  # 跳过第一行
datas

array([[2020.,   56.],
       [2021.,   48.],
       [2022.,   78.]])

## 创建数组

In [12]:
# 一般用列表去创建
print(np.array([1,2,3]),type(np.array([1,2,3])))
# 向上转换
print(np.array([1.0,2,3]))
# 自义定数据类型
print(np.array([1,2,3],dtype='float32'))
# 列表推导式
print(np.array([i for i in range(1,4)]))

[1 2 3] <class 'numpy.ndarray'>
[1. 2. 3.]
[1. 2. 3.]
[1 2 3]


In [19]:
# 全零数组
np.zeros([3,3],dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
# 全一数组
np.ones([3,3],dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
# 全是一个特定值数组
np.full([3,3],3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [24]:
# 线性定步长数组
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [25]:
# 线性定长数组
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
# 单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# 随机0-1均匀分布
np.random.random([3,3])

array([[0.59293684, 0.49771022, 0.48960677],
       [0.03606951, 0.49223748, 0.5821016 ],
       [0.64193147, 0.54725748, 0.93691189]])

In [29]:
# 随机正态分布数组(均值0，标准差1,)
np.random.normal(0,1,[3,3])

array([[-0.00501102,  0.40129366,  0.99769825],
       [-0.67094819, -1.12539403, -0.69537214],
       [ 0.0060821 , -1.38601887,  0.54184239]])

In [30]:
# 随机0-10的整数数组
np.random.randint(0,10,[3,3])

array([[6, 1, 6],
       [8, 1, 3],
       [0, 2, 5]])

In [35]:
# 内存空间任意满足条件的数组
np.empty([3,3])

array([[0.00501102, 0.40129366, 0.99769825],
       [0.67094819, 1.12539403, 0.69537214],
       [0.0060821 , 1.38601887, 0.54184239]])

## 操作数组

+ 查看数组属性：ndim、shape、size

In [43]:
np.random.seed(1)  # 设置随机种子
x1 = np.random.randint(10,size=6)  # 一维数组
x2 = np.random.randint(10,size=[3,4])  # 二维数组
x3 = np.random.randint(10,size=[3,4,5])  # 三维数组

print('x3 ndim:',x3.ndim)  # 查看有几维度
print('x3 shape:',x3.shape)  # 查看每个维度的大小
print('x3 size:',x3.size)  # 查看元素个数

print('x3 dtype:',x3.dtype)  # 查看数组里面元素类型
print('itemsize:',x3.itemsize,'bytes')  # 查看数组里面的元素字节大小
print('x3 nbytes:',x3.nbytes,'bytes')  # 查看数组总字节大小

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 dtype: int32
itemsize: 4 bytes
x3 nbytes: 240 bytes


+ 索引（点）&切片（片）

In [55]:
# python从0开始计数
x1 = np.array([1,2,3,4])# 一维数组
x2 = np.array([[5,6,7,8],
               [9,1,3,2]])  # 二维数组
x3 = np.array([[[1,3,4,5],
                [6,9,3,4]],
               
               [[2,5,7,9],
                [6,1,5,2]]])  # 三维数组

print('x1第1个元素:',x1[0])
print('x1的1-3个元素:',x1[0:3])

print('x2第1行1列个元素:',x2[0,0])
print('x2的2列3列所有元素:\n',x2[:,1:3])

print('x3第1维1行1列个元素:',x3[0,0,0])
print('x3的所有维2列3列元素:\n',x3[:,:,1:3])

# 利用索引修改值
print('原x1:',x1)
x1[0] = 9
print('修改后:',x1)

x1第1个元素: 1
x1的1-3个元素: [1 2 3]
x2第1行1列个元素: 5
x2的2列3列所有元素:
 [[6 7]
 [1 3]]
x3第1维1行1列个元素: 1
x3的所有维2列3列元素:
 [[[3 4]
  [9 3]]

 [[5 7]
  [1 5]]]
原x1: [1 2 3 4]
修改后: [9 2 3 4]


In [56]:
# 逆序
x1 = x1[::-1]
x1

array([4, 3, 2, 9])

numpy里面切片出来的是视图，视图修改原原数据也会被修改，<br>
意味着处理大型数据集时，可以获取要修改的片段进行修改，达到减小开销的作用

In [57]:
# 创建副本是单独的方法
x1_duplicate = x1.copy()
x1_duplicate

array([4, 3, 2, 9])

+ 变形

In [67]:
# 法一reshape
example1 = np.arange(1,10)
print('example1:',example1,example1.shape)

print()

example2 = example.reshape(3,3)
print('example2:\n',example2,example2.shape)

print()

example3 = example.reshape(1,9)
print('example3:',example3,example3.shape)

print()

example4 = example.reshape(9,1)
print('example4:',example4,example4.shape)

example1: [1 2 3 4 5 6 7 8 9] (9,)

example2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)

example3: [[1 2 3 4 5 6 7 8 9]] (1, 9)

example4: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] (9, 1)


In [91]:
# 法二newaxis(以现有元素数目新加一个维度)
example1[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [92]:
example1[:,np.newaxis].shape

(9, 1)

+ 拼接

In [12]:
x = np.array([[1,2,3],
              [1,2,3]])
y = np.array([[4,5,6],
              [4,5,6]])
z = np.array([[7,8,9],
              [7,8,9]])

In [13]:
# 法一
np.concatenate([x,y,z],axis=0)  #  垂直拼接

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [15]:
np.concatenate([x,y,z],axis=1)  # 水平拼接

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
np.vstack([x,y,z])  # 垂直拼接

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [17]:
np.hstack([x,y,z])  # 水平拼接

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
m = np.array([[[1,2,3],
               [1,2,3]],
             
              [[1,1,1],
               [2,2,2]]])
n = np.array([[[4,5,6],
               [4,5,6]],
             
              [[2,2,2],
               [3,3,3]]])

np.dstack([m,n])  # 深度拼接

array([[[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]],

       [[1, 1, 1, 2, 2, 2],
        [2, 2, 2, 3, 3, 3]]])

+ 分裂(拼接的逆)

In [45]:
x = np.array([[1,2,3,4,5],
              [5,6,7,8,9],
              [1,2,3,4,5]])
x1,x2,x3 = np.split(x,[1,2])  # 垂直分割
x1,x2,x3

(array([[1, 2, 3, 4, 5]]), array([[5, 6, 7, 8, 9]]), array([[1, 2, 3, 4, 5]]))

In [48]:
x1,x2,x3 = np.split(x,[2,4],axis=1)  # 水平分割
x1,x2,x3

(array([[1, 2],
        [5, 6],
        [1, 2]]),
 array([[3, 4],
        [7, 8],
        [3, 4]]),
 array([[5],
        [9],
        [5]]))

In [49]:
x1,x2,x3 = np.vsplit(x,[1,2])  # 垂直分割
x1,x2,x3

(array([[1, 2, 3, 4, 5]]), array([[5, 6, 7, 8, 9]]), array([[1, 2, 3, 4, 5]]))

In [51]:
x1,x2,x3 = np.hsplit(x,[2,4])  # 水平分割
x1,x2,x3

(array([[1, 2],
        [5, 6],
        [1, 2]]),
 array([[3, 4],
        [7, 8],
        [3, 4]]),
 array([[5],
        [9],
        [5]]))

In [59]:
x = np.array([[[4,5,6],
               [4,5,6]],
             
              [[2,2,2],
               [3,3,3]]])

np.dsplit(x,[1,2])  # 深度分割

[array([[[4],
         [4]],
 
        [[2],
         [3]]]),
 array([[[5],
         [5]],
 
        [[2],
         [3]]]),
 array([[[6],
         [6]],
 
        [[2],
         [3]]])]